### ISSUE TITLE
"AttributeError: 'NoneType' object has no attribute 'strftime'" error

### ISSUE THREAD

**Issue by SR-G** [mtimkovich/plex2letterboxd#4] opened 2021-09-05 14:45 UTC
While using the latest `plex2letterboxd` code, under linux, with an up-to-date PLEX server, i sometimes encounter this error (not on all libraries - some are working fine, some are failing) : 

```
16:38 sergio@solaris ~/plex2letterboxd% time python -m plex2letterboxd --ini config.ini --sections "Séries - TV" --output letterboxd-series.csv
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/users/sergio/plex2letterboxd/plex2letterboxd/__main__.py", line 4, in <module>
    plex2letterboxd.main()
  File "/home/users/sergio/plex2letterboxd/plex2letterboxd/plex2letterboxd.py", line 61, in main
    write_csv(sections, args.output)
  File "/home/users/sergio/plex2letterboxd/plex2letterboxd/plex2letterboxd.py", line 45, in write_csv
    date = movie.lastViewedAt.strftime('%Y-%m-%d')
AttributeError: 'NoneType' object has no attribute 'strftime'
python -m plex2letterboxd --ini config.ini --sections "Séries - TV" --output  2.14s user 0.04s system 6% cpu 34.920 total
```

To be noted : the code is running fine for several items, but then at some point (here after 150 entries) i encounter one item that is generating this issue - would be interesting if the item name was somehow displayed / identifiable.

**Comment by mtimkovich** [comment] 2022-05-05 15:58
The cause of this seems to be some watched movies not having `lastViewedAt` set. Should be fixed now.

**Closed as completed by mtimkovich** 2022-05-05 15:58 UTC
